# cfopt Version Hash Generator
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$outputFile = Join-Path $scriptDir 'version.txt'

Write-Host '  [INFO] Scanning project files...' -ForegroundColor Cyan
Write-Host ''

$header = @"
# ============================================================
# Cloudflare IP Optimizer - Version Management
# Format: KEY=VERSION:SHA256
# Auto-generated by deploy.bat/deploy.sh
# ============================================================

"@
Set-Content -Path $outputFile -Value $header -Encoding UTF8

$fileMap = [ordered]@{
    'CFOPT' = 'cfopt.sh'
    'CF_IP_MENU' = 'modules/cf-ip/menu.sh'
    'CF_IP_CORE' = 'modules/cf-ip/core.sh'
    'CF_DNS_CORE' = 'modules/cf-dns/core.sh'
    'CF_DNS_SETUP' = 'modules/cf-dns/setup.sh'
    'DNSPOD_CORE' = 'modules/dnspod-dns/core.sh'
    'DNSPOD_SETUP' = 'modules/dnspod-dns/setup.sh'
    'SCHEDULER_RUN' = 'modules/scheduler/run.sh'
    'IP_SYNC' = 'modules/ip-sync/sync.sh'
}

foreach ($key in $fileMap.Keys) {
    $file = $fileMap[$key]
    $fullPath = Join-Path $scriptDir $file
    
    if (Test-Path $fullPath) {
        $ver = '0.1'
        $content = Get-Content $fullPath -Encoding UTF8
        foreach ($line in $content) {
            if ($line -match '^SCRIPT_VERSION\s*=\s*"([^"]+)"') {
                $ver = $matches[1]
                break
            }
        }
        
        $hash = (Get-FileHash $fullPath -Algorithm SHA256).Hash
        $line = "$key=$ver`:$hash"
        Add-Content -Path $outputFile -Value $line -Encoding UTF8
        
        Write-Host "  [INFO] $key : v$ver" -ForegroundColor Green
    } else {
        Write-Host "  [WARN] $key : File not found ($file)" -ForegroundColor Yellow
    }
}

Write-Host ''
Write-Host '[OK] version.txt updated successfully.' -ForegroundColor Green
